#@ load("@ytt:data", "data")
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ data.values.scanner.serviceAccount
  namespace: #@ data.values.namespace
  #@ if data.values.scanner.serviceAccountAnnotations != None and len(data.values.scanner.serviceAccountAnnotations) > 0:
  annotations: #@ data.values.scanner.serviceAccountAnnotations
  #@ end
secrets:
#@ if/end data.values.targetImagePullSecret != None and len(data.values.targetImagePullSecret) > 0:
- name: #@ data.values.targetImagePullSecret
#@ if/end data.values.targetSourceSshSecret != None and len(data.values.targetSourceSshSecret) > 0:
- name: #@ data.values.targetSourceSshSecret
#@ if/end data.values.metadataStore.caSecret.name != None and len(data.values.metadataStore.caSecret.name) > 0:
- name: #@ data.values.metadataStore.caSecret.name
#@ if/end data.values.metadataStore.authSecret.name != None and len(data.values.metadataStore.authSecret.name) > 0:
- name: #@ data.values.metadataStore.authSecret.name
#@ if data.values.scanner.pullSecret != None and len(data.values.scanner.pullSecret) > 0:
imagePullSecrets:
- name: #@ data.values.scanner.pullSecret
#@ end