#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "ScanTemplate"}), expects="1+"
---
spec:
  template:
    initContainers:
    #@overlay/match by=overlay.subset({"name": "scan-plugin"}), expects="1+"
    - name: scan-plugin 
      #@overlay/match missing_ok=True
      resources: #@ data.values.resources