#@ load("@ytt:data","data")
---
apiVersion: scanning.apps.tanzu.vmware.com/v1beta1
kind: ScanTemplate
metadata:
  name: public-source-scan-template
spec:
  template:
    #@ if data.values.scanner.pullSecret == None:
    #@ elif len(data.values.scanner.pullSecret) > 0:
    imagePullSecrets:
      - name: #@ data.values.scanner.pullSecret
    #@ end
    containers:
    - args:
      - process
      - -f
      - /workspace
      command:
      - /aggregator
      image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:8d3532aa247b1a38bab0677d1f6dc2aec65fb23d81ef188be149ef2efad899b2
      imagePullPolicy: IfNotPresent
      name: summary
      volumeMounts:
      - mountPath: /workspace
        name: workspace
        readOnly: true
    initContainers:
    - args:
      - -c
      - mkdir /workspace/source
      command:
      - /bin/bash
      image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:60ce084d6d6fbfd83f642399a97ca329aa97d551dfdf9482e919eaa2f6d5c988
      imagePullPolicy: IfNotPresent
      name: initialize-scanner-workspace
      volumeMounts:
      - mountPath: /workspace
        name: workspace
        readOnly: false
    - args:
      - -c
      - ./source/clone-repo.sh /workspace/source/repo $(REPOSITORY)
      command:
      - /bin/bash
      image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:60ce084d6d6fbfd83f642399a97ca329aa97d551dfdf9482e919eaa2f6d5c988
      imagePullPolicy: IfNotPresent
      name: repo
      volumeMounts:
      - mountPath: /workspace
        name: workspace
        readOnly: false
    - args:
      - -c
      - scan-source.sh /workspace/source/scan.json /workspace/source/out.yaml /workspace/source/repo git
      command:
      - /bin/bash
      env:
      - name: XDG_CACHE_HOME
        value: /.cache
      image: ghcr.io/vrabbi-tap/trivy-scanner:0.2.0@sha256:b2cd41b4fc412534617a56e385fcad32eae93a144bf2b2bfd52b4eb283769f2e
      imagePullPolicy: IfNotPresent
      name: scan-plugin
      resources:
        limits:
          cpu: 1000m
        requests:
          cpu: 250m
          memory: 128Mi
      volumeMounts:
      - mountPath: /workspace
        name: workspace
        readOnly: false
      - mountPath: /.cache
        name: cache
        readOnly: false
    #@ if data.values.metadataStore != None and data.values.metadataStore.url != None and len(data.values.metadataStore.url) > 0:
    - args:
      - -c
      - |
        set -euo pipefail
        if [[ -z ${METADATA_STORE_ACCESS_TOKEN:-""} ]]
        then
          METADATA_STORE_ACCESS_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
        fi
        /insight config set-target $METADATA_STORE_URL --ca-cert /metadata-store/ca.crt --access-token $METADATA_STORE_ACCESS_TOKEN
      command:
      - bash
      env:
      - name: METADATA_STORE_URL
        value: https://metadata-store-app.metadata-store.svc.cluster.local:8443
      image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:a3c815b36d0439b4e750ff9e5a040c1d635d04f80ad60e3b40bb2bd8fb26f1d8
      imagePullPolicy: IfNotPresent
      name: metadata-store-plugin-config
      volumeMounts:
      - mountPath: /workspace
        name: workspace
        readOnly: false
      - mountPath: /.config
        name: insight-config
        readOnly: false
    - args:
      - source
      - add
      - --cyclonedxtype
      - json
      - --path
      - /workspace/source/scan.json
      command:
      - /send-scan-results.sh
      image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:a3c815b36d0439b4e750ff9e5a040c1d635d04f80ad60e3b40bb2bd8fb26f1d8
      imagePullPolicy: IfNotPresent
      name: metadata-store-plugin
      volumeMounts:
      - mountPath: /workspace
        name: workspace
        readOnly: false
      - mountPath: /.config
        name: insight-config
        readOnly: false
    #@ end
    - args:
      - check
      - --policy
      - $(POLICY)
      - --scan-results
      - /workspace/source/scan.json
      - --parser
      - json
      - --format
      - yaml
      - --output
      - /workspace/compliance-plugin/out.yaml
      command:
      - /compliance
      image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:e6435a71a9a56e1ebb13c913f23eb5ef73623e8635da9b2dbe774442eea414e6
      imagePullPolicy: IfNotPresent
      name: compliance-plugin
      volumeMounts:
      - mountPath: /workspace
        name: workspace
        readOnly: false
    restartPolicy: Never
    securityContext:
      runAsNonRoot: true
    serviceAccountName: scanner
    volumes:
    - emptyDir: {}
      name: workspace
    - emptyDir: {}
      name: insight-config
    - emptyDir: {}
      name: cache
