#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Deployment"}), expects="1+"
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name": "trivy"}), expects="1+"
      - name: trivy
        #@overlay/match missing_ok=True
        resources: #@ data.values.resources
