---
apiVersion: v1
stringData:
  values.yaml: |
    namespace: trivy-test
kind: Secret
metadata:
  name: trivy-scanner-values
  namespace: tap-install
type: Opaque
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: trivy-scanner
  namespace: tap-install
spec:
  packageRef:
    refName: trivy-scanner.scanning.tap.vrabbi.cloud
    versionSelection:
      constraints: 0.2.0
      prereleases: {}
  paused: false
  serviceAccountName: tap-install-sa
  values:
  - secretRef:
      name: trivy-scanner-values
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: trivy-server
  namespace: tap-install
spec:
  packageRef:
    refName: trivy-server.scanning.tap.vrabbi.cloud
    versionSelection:
      constraints: 0.2.0
      prereleases: {}
  paused: false
  serviceAccountName: tap-install-sa
