#@data/values
---
namespace: default
scanner:
  pullSecret: scanner-secret-ref
  docker:
    username:
    password:
    server:
  serviceAccount: scanner
  serviceAccountAnnotations:
metadataStore:
  url: https://metadata-store-app.metadata-store.svc.cluster.local:8443
  caSecret:
    name: app-tls-cert
    importFromNamespace: metadata-store
  authSecret:
    name:
    importFromNamespace:
  clusterRole: metadata-store-read-write
targetImagePullSecret:
targetSourceSshSecret:
resources:
  limits:
    cpu: 1000m
  requests:
    cpu: 250m
    memory: 128Mi
trivyServer: 
  url: http://trivy-server.trivy-system.svc.cluster.local:8080
