apiVersion: v1
kind: Namespace
metadata:
  name: trivy-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trivy-server
  name: trivy-server
  namespace: trivy-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-server
  strategy: {}
  template:
    metadata:
      labels:
        app: trivy-server
    spec:
      containers:
      - image: aquasec/trivy
        name: trivy
        command: ["trivy"]
        args: ["server","--listen","0.0.0.0:8080"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trivy-server
  name: trivy-server
  namespace: trivy-system
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: trivy-server
  type: ClusterIP
